Add intersection and union
msales/gox pull request #23
Opened 2022-10-07 10:58 UTC by kubakl

2022-10-11 15:12 UTC, hsequeda commented on gofp/intersection.go
> +	occurrences := make(map[T]int, 0)
Instead of map[T]int, you can use map[T]struct{}, and you can verify if the item exists with: val, ok:= occurrences[element]

2022-10-11 15:12 UTC, hsequeda commented on gofp/intersection.go
> +func Intersection[T comparable](lists ...[]T) []T {
Also, is good to define the T as comparable, but that limit the usage of the function to only objects that contains only 'comparable' fields, as I know this interface cannot be implemented. So, if isn't possible to implement comparable with any object, then you should use another approach, by example in the other functions I pass the list and the predicate function that contains the match criteria.

2022-10-11 15:12 UTC, hsequeda commented on gofp/union.go
> +func Union[T comparable](lists ...[]T) []T {
The same as Intersection

2022-10-11 15:12 UTC, hsequeda commented on gofp/intersection_test.go
> +		{
Add examples with more complex objects

2022-10-11 15:12 UTC, hsequeda commented on gofp/union_test.go
> +	}{
Add examples with more complex objects

2022-10-11 15:13 UTC, hsequeda commented on gofp/intersection.go
> +func Intersection[T comparable](lists ...[]T) []T {
Add comments to this function.

2022-10-11 16:05 UTC, kubakl commented on gofp/intersection.go
> +func Intersection[T comparable](lists ...[]T) []T {
done

2022-10-11 16:05 UTC, kubakl commented on gofp/union.go
> +func Union[T comparable](lists ...[]T) []T {
done

2022-10-11 16:06 UTC, kubakl commented on gofp/intersection.go
> +func Intersection[T comparable](lists ...[]T) []T {
done

2022-10-11 16:07 UTC, kubakl commented on gofp/union_test.go
> +	}{
done

2022-10-19 11:51 UTC, Skandalik requested changes

2022-10-19 11:51 UTC, Skandalik commented on gofp/intersection.go
> +	lists := make([][]T, 0)
Add allocation to benchmarks. This kind of stuff should be fast and make as little allocations as needed. Maybe it would be better to use maps here to use something like `checkLists`. Maybe `Contains` functions would be helpful https://github.com/msales/gox/blob/master/gofp/contains.go

2022-10-19 13:48 UTC, tsknadaj commented on gofp/intersection.go
> +	lists := make([][]T, 0)
Allocation added.
Yeah it will be better to use maps, Kuba make it in this way, but as Henry suggest, i move function from `comparable` into `any` type so i can't use map here to check and i can't use this contain (it works on `comparable`). But as Henry help me, i adapt code in the much better way.

2022-10-19 18:53 UTC, tsknadaj approved these changes

2022-10-21 06:07 UTC, merged